<?php

namespace UTTGescusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * regleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regleRepository extends EntityRepository
{
}
